version: '3'

services:
  simplesamlphp:
    build:
      context: "./"
      dockerfile: Dockerfile
    env_file:
      - "./.env"
    container_name: simplesamlphp-idp
    command: >
      bash -c "apachectl -D FOREGROUND"
    ports:
      - 8443:443
